### ISSUE TITLE
EPERM, operation not permitted - symlink - Windows

### ISSUE THREAD

**Issue by leeroybrun** [kmohrf/connect-fonts-fontawesome#1]
Hello,

I have an error with the symlinks on Windows, as they are not authorized for "standard" users.

Error: EPERM, operation not permitted 'node_modules\connect-fonts-fontawesome\node_modules\font-awesome\fonts\fontawesome-webfont.eot'
    at Object.fs.symlinkSync (fs.js:730:18)
    at Object.<anonymous> (node_modules\connect-fonts-fontawesome\index.js:14:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> 

I will try to find a solution, and will eventually send you a pull request. If you have an idea too, it would be great ! :-)

Thanks.

**Comment by leeroybrun** [comment]
What do you think about this ? https://github.com/leeroybrun/connect-fonts-fontawesome/commit/12277608b8a0be98847c92ed22e361c15b57a684

It's a bit dirtier than symlinks, but will works everywhere.

**Comment by kmohrf** [comment]
really bugs me that symlinks don’t work on windows. anyway. you’re solution is fine with me.
2 little remarks: in line 21 it’s "doesn’t" instead of "don’t", in line 33 I’d prefer the !== operator. feel free to open up a pull request. ready to merge when you are :)

**Comment by leeroybrun** [comment]
Great, it's fixed and submited. :)

**Comment by kmohrf** [comment]
merged in #2
